### ISSUE TITLE
Context for Channel Header  Bindings

### ISSUE THREAD

**Issue by danilvalov** [mattermost/mattermost-app-examples#23]
I use [your TS example](https://github.com/mattermost/mattermost-app-examples/blob/master/typescript/hello-world/src/app.ts#L76-L86).
But when I try to use `req.body` context from [/bindings](https://github.com/mattermost/mattermost-app-examples/blob/master/typescript/hello-world/src/app.ts#L114) request there are not context fields from [the official documentation](https://developers.mattermost.com/integrate/apps/structure/bindings/#call-context-data): `user_id`, `channel_id`, `team_id` for the `/channel_header` bindings request.

I receive the following `req.body` data in the `/bindings` request for the `/channel_header` location:
```json
{
  "path":"/bindings",
  "context":{
    "app_id":"",
    "mattermost_site_url":"https://my-server",
    "app_path":"/plugins/com.mattermost.apps/apps/my-app-name",
    "bot_user_id":"{BOT_USER_ID}",
    "bot_access_token":"{BOT_USER_TOKEN}",
    "oauth2":{}
  }
}
```

Also I tried to add a `depends_on_channel` option to my `channelHeaderBindings` config (and I don't know what this option means, no any information about this field in the documentation). Also I tried to change location for bindings:
```ts
const channelHeaderBindings: AppBinding = {
  app_id: manifest.app_id,
  label: manifest.display_name,
  location: '/channel_header',
  depends_on_channel: true,
  bindings: [
    {
      app_id: manifest.app_id,
      location: '/channel_header',
      icon: 'icon.jpg',
      label: 'Button label',
      depends_on_channel: true,
      form
    }
  ]
};
```
No any positive results after changes above.

How to fix it?

Envs:
Mattermost Version: **9.7.3**
Mattermost App Example: [latest version](https://github.com/mattermost/mattermost-app-examples/blob/master/typescript/hello-world/src/app.ts#L76-L86)

**Comment by azigler** [comment]
Thanks for reaching out with this question. I'm not quite sure what's causing this problem.

@mickmister could you check out this issue from Danil?

**Comment by mickmister** [comment]
Hi @danilvalov, to get the channel in the context of the bindings request, you'll need to specify a bindings `call` in the manifest, and have it include the current channel in its `expand`:

https://github.com/mattermost/mattermost-plugin-apps/blob/36b0fffc2600916c54abeac6bf047d76bf627e85/apps/manifest.go#L78

```ts
const manifest = {
  id: 'my_app_id',
  bindings: {
    path: '/bindings',
    expand: {
      channel: 'all'
    }
  }
};
```

Then the bindings request should contain the channel in the request's context

Please let me know if this works. Thanks :+1:

**Comment by danilvalov** [comment]
@mickmister Sorry, but your solution doesn't work for me.
My `req.body` after adding changes above:
```js
{
  path: '/bindings',
  expand: { channel: 'all' },
  context: {
    app_id: '',
    mattermost_site_url: 'http://localhost:8065',
    developer_mode: true,
    app_path: '/plugins/com.mattermost.apps/apps/teammate-feedback',
    bot_user_id: 'xb4wfcx6qiynbf1pdx77qrpo6y',
    bot_access_token: 'c9ecnz3outfkjk5hq5nwcwhyia',
    oauth2: {}
  }
}
```

My manifest:
```ts
const manifest: AppManifest = {
  app_id: 'test-app',
  display_name: 'Test App',
  description: 'Test app for Mattermost',
  app_type: 'http',
  icon: 'icon.jpg',
  http: {
    root_url
  },
  bindings: {
    path: '/bindings',
    expand: {
      channel: 'all',
    }
  },
  requested_permissions: [
    Permission.ActAsBot
  ],
  requested_locations: [
    Locations.ChannelHeader,
    Locations.Command
  ]
};
```

**Comment by mickmister** [comment]
@danilvalov Are you seeing any errors in the MM server logs when this request is being made?

**Comment by danilvalov** [comment]
@mickmister When installing the app I see the following error logs:
```json
{
   "timestamp":"2024-06-04 20:53:50.977 Z",
   "level":"debug",
   "msg":"failed to expand field channel",
   "caller":"app/plugin_api.go:970",
   "plugin_id":"com.mattermost.apps",
   "destination":"teammate-feedback",
   "from_user_id":"wc9e7tpgrb8b5jxj6u536c4peo",
   "error":"no channel ID to expand",
   "plugin_caller":"server/proxy/expand.go:197",
   "request_id":"ca1kua8usidwjcahjxw9676bpc"
}

{
   "timestamp":"2024-06-04 20:53:50.992 Z",
   "level":"debug",
   "msg":"You do not have the appropriate permissions.",
   "caller":"web/context.go:113",
   "path":"/api/v4/channels/itcs5n4ufpdoupb899tgtrrkcc",
   "request_id":"h1npg754zjf4by6rufarhhpf3e",
   "ip_addr":"127.0.0.1",
   "user_id":"xb4wfcx6qiynbf1pdx77qrpo6y",
   "method":"GET",
   "err_where":"Permissions",
   "http_code":403,
   "error":"Permissions: You do not have the appropriate permissions., userId=xb4wfcx6qiynbf1pdx77qrpo6y, permission=read_public_channel,"
}

{
   "timestamp":"2024-06-04 20:53:50.992 Z",
   "level":"debug",
   "msg":"failed to expand field channel",
   "caller":"app/plugin_api.go:970",
   "plugin_id":"com.mattermost.apps",
   "from_user_id":"wc9e7tpgrb8b5jxj6u536c4peo",
   "path":"/api/v1/bindings",
   "error":"id: itcs5n4ufpdoupb899tgtrrkcc: : You do not have the appropriate permissions., userId=xb4wfcx6qiynbf1pdx77qrpo6y, permission=read_public_channel,",
   "plugin_caller":"server/proxy/expand.go:197",
   "destination":"teammate-feedback",
   "request_id":"jxpc386j43y9mbg5auzaai8ibc"
}
```

P.S. For this test I used Mattermost Server 7.9.0 from `docker-compose.yml` in this repo

**Comment by mickmister** [comment]
Since we fetch this channel info with the user's token, you'll also need to include `act_as_user` in your `manifest.requested_permissions`. Please let me know if this fixes the issue @danilvalov. Thanks

**Comment by danilvalov** [comment]
@mickmister Yes, it works! Thank you!

So finally, for the developers with the same issue.
To get channel info in Apps we need to add the following to the manifest:
1. `expand: { channel: 'all' }` to `bindings` section
2. `act_as_user` to `requested_permissions`

Example:
```js
const manifest = {
  app_id: 'your_app_id',
  bindings: {
    path: '/bindings',
    expand: {
      channel: 'all'
    }
  },
  requested_permissions: [
    'act_as_user',
    ...
  ],
  ...
};
```

**Comment by mickmister** [comment]
@danilvalov I'm curious about your use case of using the channel during this bindings call? It's not uncommon but I'd like to understand the use case if you can share

**Comment by danilvalov** [comment]
@mickmister I receive all data about channels:
```js
{
  path: '/bindings',
  expand: { channel: 'all' },
  context: {
    app_id: '',
    mattermost_site_url: 'http://localhost:8065',
    developer_mode: true,
    app_path: '/plugins/com.mattermost.apps/apps/my-app-name,
    bot_user_id: 'xb4wfcx6qiynbf1pdx77qrpo6y',
    bot_access_token: 'og7b7idyxtyr8ctcq1q1jfuywc',
    channel: {
      id: 'sug7d48wqbd4bdb6zydqiocszr',
      create_at: 1717529346767,
      update_at: 1717529346767,
      delete_at: 0,
      team_id: '',
      type: 'D',
      display_name: '',
      name: 'wc9e7tpgrb8b5jxj6u536c4peo__wc9e7tpgrb8b5jxj6u536c4peo',
      header: '',
      purpose: '',
      last_post_at: 0,
      total_msg_count: 0,
      extra_update_at: 0,
      creator_id: 'wc9e7tpgrb8b5jxj6u536c4peo',
      scheme_id: null,
      props: null,
      group_constrained: null,
      shared: false,
      total_msg_count_root: 0,
      policy_id: null,
      last_root_post_at: 0
    },
    oauth2: {}
  }
}
```

**Comment by danilvalov** [comment]
@mickmister Sorry, I misunderstood you initially.

My case is simple: I want to make an app that allows users to send feedback about colleagues directly from Mattermost. I need to define a channel in order to immediately substitute the ID of the desired person in the “To” field automatically.

I also plan to make an app that will allow you to quickly assign tasks to an user and send them to our internal Task Tracker system.
